server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/delay?useUnicode=TRUE&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=FALSE&rewriteBatchedStatements=TRUE&useServerPrepStmts=TRUE&profileSQL=false&logger=Slf4JLogger&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

#  RocketMQProperties
rocketmq:
  name-server: ${mq.namesrv}
  producer:
    group: mpzdormu_server
    sendMessageTimeout: 30000

mock:
  push: 0






