spring:
  datasource:
    url: jdbc:mysql://224.220.184.17:3306/delay?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: p@ssw0rd
  jdbctemplate:
    fetch-size: -1
    max-rows: -1

  redis:
    password: nTDnELCqwF9DCb9
    cluster:
      nodes: test-redis-1.dlab.cn:9000,test-redis-1.dlab.cn:9001,test-redis-3.dlab.cn:9000,test-redis-3.dlab.cn:9001,test-redis-2.dlab.cn:9000,test-redis-2.dlab.cn:9001
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
        max-wait: 5000
        time-between-eviction-runs: 1


#  RocketMQProperties
rocketmq:
  name-server: 192.168.4.34:9876
  consumer:
    group: mpzdormu_receive_group
    topics: mpzdormu_topic
  producer:
    group: mpzdormu_server
    sendMessageTimeout: 30000


mock:
  push: 1

queue:
  size: 4

