spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx.xx:3306/delay?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: xxxx

  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

#  RocketMQProperties
rocketmq:
  name-server: xxx.xxx.xxx.xx:9876
  producer:
    group: mpzdormu_server
    sendMessageTimeout: 30000

mock:
  push: 0




